CREATE DATABASE dokoTsubu;

CREATE TABLE matters
(id SERIAL PRIMARY KEY,
 user_name VARCHAR NOT NULL,
 text VARCHAR);

CREATE TABLE users
(user_name VARCHAR NOT NULL PRIMARY KEY,
 pass VARCHAR NOT NULL);
